{{ config(materialized="table",) }}
WITH source AS (
  SELECT
    *
  FROM
     {{ ref('raw_payments') }}
),
renamed AS (
  SELECT
    id AS payment_id,
    order_id,
    payment_method,
    amount / 100 AS amount
  FROM
    source
)
SELECT
  payment_id,
  order_id,
  payment_method,
  amount
FROM
  renamed

-- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
