{{ config(materialized="ephemeral",) }}
WITH source AS (
  SELECT
    *
  FROM
     {{ ref('raw_orders') }}
),
renamed AS (
  SELECT
    id AS order_id,
    user_id AS customer_id,
    order_date,
    status
  FROM
    source
)
SELECT
  order_id,
  customer_id,
  order_date,
  status
FROM
  renamed

-- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
