WITH orders AS (
  SELECT
    *
  FROM
     {{ ref('stg_orders') }}
),
customer_orders AS (
  SELECT
    customer_id,
    MIN(order_date) AS first_order,
    MAX(order_date) AS most_recent_order,
    COUNT(*) AS number_of_orders
  FROM
    orders
  GROUP BY
    customer_id
),
payments AS (
  SELECT
    *
  FROM
     {{ ref('stg_payments') }}
),
customer_payments AS (
  SELECT
    orders.customer_id,
    SUM(payments.amount) AS total_amount
  FROM
    payments
    LEFT JOIN orders ON payments.order_id = orders.order_id
  GROUP BY
    orders.customer_id
),
customers AS (
  SELECT
    *
  FROM
     {{ ref('stg_customers') }}
)
SELECT
  c.customer_id,
  c.first_name,
  c.last_name,
  o.first_order,
  o.most_recent_order,
  o.number_of_orders,
  p.total_amount AS customer_lifetime_value
FROM
  customers AS c
  LEFT JOIN customer_orders AS o ON c.customer_id = o.customer_id
  LEFT JOIN customer_payments AS p ON o.customer_id = p.customer_id

-- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
