{% set payment_methods = ['credit_card', 'coupon', 'bank_transfer', 'gift_card'] %}
WITH payments AS (
  SELECT
    *
  FROM
     {{ ref('stg_payments') }}
),
order_payments AS (
  SELECT
    order_id,
    SUM(amount) AS total_amount
  FROM
    payments
  GROUP BY
    order_id
),
orders AS (
  SELECT
    *
  FROM
     {{ ref('stg_orders') }}
),
final AS (
  SELECT
    orders.order_id,
    orders.customer_id,
    orders.order_date,
    orders.status,
    order_payments.total_amount AS amount
  FROM
    orders
    LEFT JOIN order_payments ON orders.order_id = order_payments.order_id
)
SELECT
  order_id,
  customer_id,
  order_date,
  status,
  amount
FROM
  final

-- Generated by PRQL compiler version 0.4.2 (https://prql-lang.org)
